- name: Copying redis repo
  ansible.builtin.copy:
    src: redis-repo
    dest: /etc/yum.repos.d/redis.repo

- name: Installing reids
  ansible.builtin.package:
    name: redis-6.2.13
    state: present

- name: Replacing IP address in the config file
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Replacing IP address in the /etc/redis/redis.conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes


