- name: Copying mongo-db repo
  ansible.builtin.copy:
    src: Mongo-repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

 name: Replacing IP address in the config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting MongoDB
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes
   
- name: Download and Extracting schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip  
    dest: /tmp
    remote_src: yes  

- name: Injecting schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{items}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users


    