- name: Demo on conditions 
  hosts: all
  vars:
   - action: true
   - action1: false
   - a: 6
  tasks:
   - name: Execute this task when Distribution is CentOS
     ansible.builtin.debug:
      msg: Welcome to CentOS
     when: ansible_distribution=="CentOS"

   - name: Execute this using true
     ansible.builtin.debug:
      msg: Prints since the action value is true
     when: action    

   - name: Execute this using true
     ansible.builtin.debug:
      msg: skips since the action value is false
     when: action1    

   - name: Execute this using not define
     ansible.builtin.debug:
      msg: prints since the var a is declared 
     when: a is defined   

   - name: Execute this using define
     ansible.builtin.debug:
      msg: prins since the var b is not declared
     when: b is not defined   
