- name: facts
  hosts: all
  tasks: 
   - name: nameOftask
     ansible.builtin.debug:
      msg: Distribution of this machine is {{ansible_distribution}} 

   - name: Printing the mac address of the remote node 
     ansible.builtin.debug:
      msg: Mac Address of this machine is {{ansible_default_ipv4.macaddress}}