- name: Demo of Ignore
  hosts: all
  tasks:
   - name: Checking nginx
     ansible.builtin.shell: ps -ef | grep nginx | grep -v grep
     ignore_errors: yes
     register: OUT

   
  
   - name: Printing the Shell Output using OUT Variable
     ansible.builtin.debug:
      msg: "{{OUT}}"
