- name: Demo of Ignore
  hosts: all
  tasks:
   - name: Checking nginx
     ansible.builtin.shell: ps -ef | grep nginx | grep -v grep
     ignore_errors: yes
    
   - name: Chech user Id
     ansible.builtin.shell: id
     register: OUT

   - name: 
     ansible.builtin.debug: 
      msg: "{{OUT}}"
