- name: Demo of Ignore
  hosts: all
  tasks:
   - name: Ignore
     ansible.builtin.shell: ps -ef | grep centos
     register: OUT

   - name: Printing the Shell Output using OUT Variable
     ansible.builtin.debug:
      msg: "{{OUT}}"
