- name: nameOfplay
  hosts: all
  tasks: 
    - name: nameOftask
      ansible.builtin.debug:
       msg: Hello from task of play 


- name: Play1
  hosts: all
  tasks:
    - name: Task1
      ansible.builtin.debug:
       msg: Printing the task1 from play1


- name: play2
  hosts: Dev
  tasks:
   - name: Only-Dev-Node
     ansible.builtin.debug:
      msg: Printing Only Dev node


- name: play3
  host:DevOps
  tasks:
   - name: Only-DevOps-Node
     ansible.builtin.debug:
      msg: Printing Only DevOps node

