- name: nameOfplay
  hosts: all
  tasks: 
    - name: nameOftask
      ansible.builtin.debug:
       msg: Hello from task1 of play1 


- name: Play1
  hosts: all
  tasks:
    - name: Task1
      ansible.builtin.debug:
       msg: Printing the task1 from play1