- name: Demo on privilege escalation
  hosts: all
  become: yes
  tasks: 
   - name: Check the user id 
     ansible.builtin.shell: id
     register: OUT

   - name: Printing the id 
     ansible.builtin.debug: 
      msg: "{{OUT.stdout_lines}}"

   - name: Demo on running script as user
     ansible.builtin.shell: id
     register: OUT1
     become_user: centos
     
   - name: printing the OUT1
     ansible.builtin.debug:
      msg: "{{OUT1.stdout}}"  

