- name: Demo of Tags
  hosts: all
  tasks:
   - name: Frontend
     ansible.builtin.debug:
      msg: this is frontend
     tag: frontend
    
   - name: Backend
     ansible.builtin.debug:
      msg: this is bakend
     tag: backend

   - name: DataBase
     ansible.builtin.debug: 
      msg: this is db
     tag: db

     
