- name: Demo of Tags
  hosts: all
  tasks:
   - name: Frontend
     ansible.builtin.debug:
      msg: this is frontend
     tags: frontend
    
   - name: Backend
     ansible.builtin.debug:
      msg: this is bakend
     tags: backend

   - name: DataBase
     ansible.builtin.debug: 
      msg: this is db
     tags: db


