- name: Demo on Using vars
  hosts: all
  vars_prompt:
   - name: PURL
     prompt: Enter the purl
     private: true
  vars_files: vars-d.yaml 
  vars:
   URL: play.google.com 
  tasks:
   - name: Global varibles
     ansible.builtin.debug:
      msg: Global varible is {{URL}}

   - name: Local vars
     ansible.builtin.debug:
      msg: Local varible is {{URL}}
     vars:
      URL: task.google.co

   - name: Print the variable without string 
     ansible.builtin.debug:
      msg: "{{URL}}"

  #  - name: Printing the value supplied from command line
  #    ansible.builtin.debug:
  #     msg: "{{CMD_URL}}"

   - name: Printing the variables from a separate vars-d.yaml file
     ansible.builtin.debug:
      msg: url variable in vars-d.yaml file is {{url}}

   - name: Printing the variables from a separate vars-d.yaml file
     ansible.builtin.debug:
      msg: game variable in vars-d.yaml file is {{Game}}

   - name: Printing prompt url  
     ansible.builtin.debug:
      msg: "{{PURL}}"