- name: Demo on Using vars
  hosts: all
  vars:
   URL: play.google.com
  tasks:
   - name: Global varibles
     ansible.builtin.debug:
      msg: Global varible is {{URL}}

   - name: Local vars
     ansible.builtin.debug:
      msg: Local varible is {{URL}}
     vars:
      URL: task.google.co

   - name: Print the variable without string 
     ansible.builtin.debug:
      msg: "{{URL}}"

   - name: Printing the value supplied from command line
     ansible.builtin.debug:
      msg: "{{CMD_URL}}"
