- name: Demo on Using vars
  hosts: all
  vars:
   URL: play.google.com
  tasks:
   - name: Global varibles
     ansible.builtin.debug:
      msg: Global varible is {{URL}}

   - name: Local vars
     ansible.builtin.debug:
      msg: Local varible is {{URL}}
     vars:
      URL: task.google.co

      