- name: Copying prometheus Config 
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
 

- name: starting prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted


- name: Waiting for the prometheus port to come up
  ansible.builtin.wait_for:
    port: 9090
    delay: 15
    timeout: 30


