- name: Creating a Roboshop User Account 
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop User Account
  register: APPUSERINFO

- name: Creating a Roboshop User Account 
  ansible.builtin.debug:  
    msg: "{{APPUSERINFO}}"