- name: Installing Maven
  ansible.builtin.package:
    name: maven
    state: present

- name: create_user 
  ansible.builtin.include_role:
    name: common 
    tasks_from: create_user

- name: Download and Extract
  ansible.builtin.include_role:
    name: common 
    tasks_from: download_extract

- name: Generating Artifacts
  ansible.builtin.shell: mvn clean package  &&  mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: config-restart 
  ansible.builtin.include_role:
    name: common
    tasks_from: config-restart

- name: Configuring rsyslog
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Configuring filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
