#checking the /home/roboshop/component directory is present or not if the dir exists then it should perfrom the clean operation else it will create
- name: checking directory existance
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes

- name: Creating a directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: directory
    mode: '0755'

- name: Downloading and extracting the artifacts from Nexus 
  become_user: "{{APPUSER}}"
  ansible.builtin.unarchive:
    src: http://172.31.13.88:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    remote_src: yes


