- name: Installing Python 3
  ansible.builtin.package:
    name:
      - python36 
      - gcc
      - python3-devel 
    state: present

- name: Calling create_user for running the application
  ansible.builtin.include_role:
    name: common 
    tasks_from: create_user

- name: calling download_extract task from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extract

- name: Fetch uid and Replace 
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid={{APPUSERINFO.uid}}

- name: Fetch gid and Replace 
  ansible.builtin.replace:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid=1'
    replace: gid={{APPUSERINFO.group}}


